### ISSUE TITLE
`test_map_association` test timing out in our CI

### ISSUE THREAD

**Issue by maxwest-uw** [astronomy-commons/hipscat-import#110]
the unit test

```
tests/hipscat_import/association/test_association_map_reduce.py::test_map_association
```

is timing out and causing the CI to fail. didn't seem to start until after #107 was merged, although I can't think of a reason why the two would be related... since it was my change that triggered this failure I'll investigate o7

**Comment by delucchi-cmu** [comment]
Likely, the real cause of this issue is that the association tests are first alphabetically, and they're taking longer to set up with the dask-on-ray client.

The association pipeline should still be removed, but we should also make it easier to tell which part of the workflow is failing and give the first dask test a longer timeout.
